name: fixa
description: "Fixa Repair Mobile Repairing App"


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_cache_manager: ^3.4.1
  video_player: ^2.9.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  intl: ^0.19.0
  geolocator: ^13.0.1
  infinite_carousel: ^1.0.3
  flutter_image_slideshow: ^0.1.6
  uuid: ^4.5.1
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  onesignal_flutter: ^5.1.4
  firebase_auth: ^5.3.2
  device_info_plus: ^10.1.2
  flutter_screenutil: ^5.9.3
  order_tracker_zen: ^1.0.0+4
  url_launcher: ^6.3.1
  icons_launcher: ^3.0.0
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^8.2.9
  flutter_widget_from_html: ^0.16.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  platforms:
    android:
      enable: true
    ios:
      enable: true



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/icons/